set_property SRC_FILE_INFO {cfile:{C:/Users/AC Tecnologia/Documents/Projetos VHDL/Vivado 2017.4/Somador 1bit/Somador 1bit.srcs/constrs_1/imports/Projetos VHDL/Basys3_Master.xdc} rfile:{../../../Somador 1bit.srcs/constrs_1/imports/Projetos VHDL/Basys3_Master.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {Cout}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports {S}]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A14 [get_ports {A}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A16 [get_ports {B}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B15 [get_ports {Cin}]
